In [21]:
import tensorflow as tf
import numpy as np
import math
from sklearn.neighbors import KNeighborsClassifier

In [2]:
dataset = np.genfromtxt('diabetes.csv', delimiter=',', skip_header=1)
np.random.seed(1)
np.random.shuffle(dataset)

In [16]:
def normalize(x):
    normalized_x = (x - np.mean(x, axis=0))/np.std(x, axis=0)
    normalized_x[:, -1] = x[:, -1]
    return normalized_x
def next_batch(X, batch_size = 32, batch_no = 0):
    '''
    batch_no starts from 0
    '''
    if batch_no >= X.shape[0]/batch_size:
        next_batch_ending_index = -1
    else:
        next_batch_ending_index = batch_size * (batch_no + 1)
    next_batch_starting_index = batch_size * batch_no
    return X[next_batch_starting_index:next_batch_ending_index, :]

In [17]:
dataset = normalize(dataset)

In [15]:
train_size_length = math.floor(dataset.shape[0] * 0.8)
training_data, test_data = dataset[:train_size_length, :], dataset[train_size_length:, :]
training_data, test_data

(array([[ 1.23388019,  0.94221523,  0.45982725, ...,  0.1332588 ,
          0.23476686,  1.        ],
        [-1.14185152, -0.40356202, -0.05715025, ...,  0.95171097,
         -0.10558415,  0.        ],
        [ 1.23388019,  1.44296956,  1.90736425, ..., -0.92680285,
          0.83038113,  1.        ],
        ...,
        [-0.84488505, -0.37226487, -0.67752325, ...,  1.09063642,
         -0.87137393,  0.        ],
        [-1.14185152,  0.34756947,  0.45982725, ..., -0.23821579,
         -1.04154944,  0.        ],
        [-0.25095213, -0.43485916, -0.36733675, ...,  0.62251803,
         -0.87137393,  1.        ]]),
 array([[ 2.7187125 , -0.46615631,  0.04624525, ..., -0.66707265,
          1.59617091,  0.        ],
        [ 0.93691372, -0.59134489,  0.25303625, ..., -0.80901822,
          1.00055664,  0.        ],
        [ 0.04601433,  0.25367803,  0.87340925, ..., -0.72747502,
         -0.87137393,  0.        ],
        ...,
        [-0.25095213, -1.24858494,  0.87340925, ..., -

In [19]:
 next_batch(training_data, batch_size=5, batch_no=1)

array([[-0.84488505, -0.184482  ,  0.04624525,  0.59362962,  0.14066744,
         0.33093202,  0.17252035, -0.10558415,  1.        ],
       [ 0.63994726, -0.56004775, -0.16054575, -1.28821221, -0.69289057,
        -0.97633621, -0.67311288, -0.36084741,  0.        ],
       [ 0.04601433, -0.09059057,  0.04624525, -1.28821221, -0.69289057,
         1.58743255,  1.30506485, -0.61611067,  0.        ],
       [ 0.63994726, -0.71653347, -0.57412775,  0.7818138 ,  0.95685965,
         0.25478047, -0.1264714 ,  0.83038113,  0.        ],
       [-0.25095213,  0.56664949, -0.78091875, -1.28821221, -0.69289057,
        -0.81134119, -0.21103473, -0.95646168,  1.        ]])

In [26]:
Xtr, Ytr, Xte, Yte = training_data[:, :-1], training_data[:, -1], test_data[:, :-1], test_data[:, -1]
Xtr.shape, Ytr.shape

((614, 8), (614,))

In [35]:
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(Xtr, Ytr)

pred = knn.predict(Xte)

accuracy = np.mean(pred == Yte, axis=0) * 100

print('Acheived accuracy of {0} %'.format(accuracy))

Acheived accuracy of 72.72727272727273 %
